---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./secrets.sops.yaml
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: mastodon
      app.kubernetes.io/instance: mastodon
configMapGenerator:
  - name: mastodon-values
    files:
      - values.yaml=mastodon-values.yaml
