apiVersion: v1
kind: ConfigMap
metadata:
    name: postgresql-secret-values
    namespace: default
data:
    values.yaml: ENC[AES256_GCM,data:SzVbBSgIValV9Bep9ctVdfKb5s0XL3TmmZ6XA0zwtLnl18IFmiTYyxnm5icRxOMzzR6K8XF3RAkeDoee/qIYgZj4TcBuvdfs1NSKpYCmAAK3r5Wo6tQiY4niAKUwdoQUHhbhduDjbUl1d+IZAV4k7mDHnucwy1tfvtr3NTFDsv55nw5CzY7yobwxjs9dR/iPz2jfLVoy6qlCm/5usiz8EbeOtpN1sfxwD9oDGLpwv12I15pFSea9zVaToQX6nxk=,iv:2JoncYe9XEcirFrUfjP0XYDmC2KiUcWBYv9MXG5D0G4=,tag:Ti9yGB4AIbdR1NpeYLE8tQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n535rsu7hlyjg0p46y6du9nl0j7ldsfcmy9x9a24kxs6tuh8dgks2engp2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtY0hlVnBodEJNNDFzSjl6
            aUFlOURxRWJTM0V3ZUtZalRjdlNhdW9YYWxNCkw5cGk5Wmh6c2cwczQzWEYyK2FQ
            ckVyRzlCeG1xNWxNYk5ZM0tDcXJGZ28KLS0tIDZvYmNZSzdKb24zWVVGdnhBREhF
            QlcvVGRHQVkrTDBoMEdST05QS2hneTAKEsoTISTqicwFigjn8KeYFgqxtweH66u2
            I3Wb3n+/unU0vw7nCTg2uYXBkMDaIUVJtdPY1uvATX2ipMB1NOqLGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-25T11:41:55Z"
    mac: ENC[AES256_GCM,data:MCrW2+RrDTXri2XUaMI6L8/rIMct1qD4yWtUg39qjrnZjtyTNN/UCXEi75IV5JWcBkOm1tXGzEalPZZVB977PYZsAue3cGHEtYC9tuDa2QIRERfY9po4lhCE0c3jG+fY+vO8sGRgQC6N7syYr0aCuI5fje7QxCjyk/5umbs8b2w=,iv:QrFgVyjkDrgszcGRwlS5j6W/iU/6mNTQD5M/TrVZOWU=,tag:9FcljRY6KmaNaS0CF4ydew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
