apiVersion: v1
kind: ConfigMap
metadata:
    name: postgresql-secret-values
    namespace: default
data:
    values.yaml: ENC[AES256_GCM,data:YeKYslcdp6k78FYXHidYYcZiUYH1o6sF4Pph/kqsiLeR4dsPaFfwz4Cg/uHCRwIrhO0zL/pvkilcX0dSbSU7jDDurZ9nGQSr4enRkwJJJ0lbmOpnX2aRk2Am2nyA0oYEtFIkxt1E0IwsWHpwxmu/0aWvHVw27QuN2wqc3+QVnS+ZvWPBTSKRRkXLvjITEZDHXOBJWEpPtBGsR9UtRYhsKvYCjmKvt3xfyXyNlUTfo7zy,iv:CcoQWKCFUvyXRObtnTxTxow6PlMyOrwYdGvHtxTb5m0=,tag:O/43U++0xjuPsBi6t6epqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n535rsu7hlyjg0p46y6du9nl0j7ldsfcmy9x9a24kxs6tuh8dgks2engp2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtY0hlVnBodEJNNDFzSjl6
            aUFlOURxRWJTM0V3ZUtZalRjdlNhdW9YYWxNCkw5cGk5Wmh6c2cwczQzWEYyK2FQ
            ckVyRzlCeG1xNWxNYk5ZM0tDcXJGZ28KLS0tIDZvYmNZSzdKb24zWVVGdnhBREhF
            QlcvVGRHQVkrTDBoMEdST05QS2hneTAKEsoTISTqicwFigjn8KeYFgqxtweH66u2
            I3Wb3n+/unU0vw7nCTg2uYXBkMDaIUVJtdPY1uvATX2ipMB1NOqLGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-24T12:18:49Z"
    mac: ENC[AES256_GCM,data:V4/exBBlWTKxWnL3NS/Ptr+vE++T982cYrG2hofYoyk6O+7v7BMiLnyNkemwVlRMceqN8lwFzng/fQDrbkrnR9mUbPqDtkGYwCWdGfA+DAbGi1lUu+Aw1QXbCq5/gC68rhV4L4HHnH3zceqCAMBzLMZtCsxB08o6fh4W/rMcGlE=,iv:BNWx3WHMSy16dl1d8DzR6P6r+1enueawNWKn/Lft0cM=,tag:XyLY6EDosb/WsPpofVaIDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
