---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-ingress-nginx
  namespace: flux-system
spec:
  path: ./kubernetes/apps/networking/ingress-nginx/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: toot-ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m

