---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mastodon
  namespace: default
spec:
  path: ./kubernetes/apps/default/mastodon/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: toot-ops
  wait: true
  interval: 10m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: server-properties
  decryption:
    provider: sops
    secretRef:
      name: sops-age