---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/kustomization_v1beta2.json
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-postgresql
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/postgresql/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: toot-ops
  wait: true
  interval: 10m
  retryInterval: 1m
  timeout: 3m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
